language: java
jdk:
  - openjdk7
  - oraclejdk7  
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'frontend' ]; then cd .. && eval "mv $currentfolder frontend" && cd frontend; fi
  - npm install -g bower grunt-cli grunt
  - bower install && npm install && grunt
